# Generated by Django 5.1.11 on 2025-06-21 03:59

import django.contrib.postgres.indexes
import django.utils.timezone
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchToken",
            fields=[
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="The token",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "added",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="The time this token was added to the database",
                    ),
                ),
            ],
            options={
                "verbose_name": "search token",
                "verbose_name_plural": "search tokens",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["token"],
                        name="searchtoken_trgm_ops",
                        opclasses=["gin_trgm_ops"],
                    )
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("tag"),
                models.Model,
            ),
        ),
    ]
