# Generated by Django 5.1.11 on 2025-06-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("didyoumean", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchtoken",
            name="disabled",
            field=models.BooleanField(
                default=False,
                help_text="Disabled tokens are not considered in search corrections",
            ),
        ),
    ]
