# Generated by Django 5.1.11 on 2025-06-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("didyoumean", "0002_searchtoken_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchtoken",
            name="popularity",
            field=models.FloatField(
                db_index=True,
                default=1.0,
                editable=False,
                help_text="The popularity of the highest-popularity release where this token originated from. If this token didn't originate from a release, this number is arbitrary (but can be supplanted if a release with a higher popularity shows up later)",
            ),
        ),
    ]
