# Generated by Django 5.1.5 on 2025-01-19 05:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OdyseeChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("handle", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="OdyseeRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("description", models.TextField()),
                ("url", models.URLField(max_length=512)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="odyseescraper.odyseechannel",
                    ),
                ),
            ],
        ),
    ]
