# Generated by Django 5.1.5 on 2025-01-19 05:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=512,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
