# Generated by Django 5.1.5 on 2025-01-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0002_alter_odyseerelease_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="thumbnail",
            field=models.URLField(default="https://notadomain.notatld", max_length=512),
            preserve_default=False,
        ),
    ]
