# Generated by Django 5.1.5 on 2025-01-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "odyseescraper",
            "0004_tag_alter_odyseechannel_id_alter_odyseerelease_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseechannel",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
