# Generated by Django 5.1.5 on 2025-01-24 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0005_odyseechannel_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="released",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
