# Generated by Django 5.1.5 on 2025-01-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0006_odyseerelease_released"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="filehash",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        ),
    ]
