# Generated by Django 5.1.5 on 2025-01-24 20:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0007_odyseerelease_filehash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseechannel",
            name="description",
            field=models.TextField(
                help_text="A user-facing description of the channel, its owners, and its content. May also contain links to related resources and websites."
            ),
        ),
        migrations.AlterField(
            model_name="odyseechannel",
            name="handle",
            field=models.CharField(
                help_text="The @tag of the user. May be a short tag (@someuser) or qualified with claimid (@someuser:4ab8)",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="odyseechannel",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="A unique identifier for this channel",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="odyseechannel",
            name="name",
            field=models.CharField(
                help_text="The human-readable name of the channel. Does not, and often will not, necessarily correlate with the channel's handle",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="channel",
            field=models.ForeignKey(
                help_text="The channel that this release came from",
                on_delete=django.db.models.deletion.CASCADE,
                to="odyseescraper.odyseechannel",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="description",
            field=models.TextField(
                help_text="A user-facing description of this release. This should mirror the official post from Odysee, if available"
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="filehash",
            field=models.CharField(
                help_text="The hash of the file of the claim", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="A unique identifier for this release. Usually the LBRY claim ID, if available",
                max_length=512,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="name",
            field=models.CharField(
                help_text="The human-readable name of this release", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="released",
            field=models.DateField(
                help_text="The date that this release was posted in UTC"
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="tags",
            field=models.ManyToManyField(
                help_text="A list of tags associated with this release. This should NOT contain extraneous tags from Odysee -- it's a data structure specific to this site.",
                to="odyseescraper.tag",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="thumbnail",
            field=models.URLField(
                help_text="The URL to the Odysee-hosted thumbnail of the release",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="url",
            field=models.URLField(
                help_text="The URL to the Odysee page where the release can be downloaded. It is NOT a direct download link",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.TextField(help_text="A user-facing description of the tag"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="A unique identifier for this tag",
                max_length=512,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="The name for this tag as it should be displayed across UIs",
                max_length=256,
            ),
        ),
    ]
