# Generated by Django 5.1.5 on 2025-01-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0008_alter_odyseechannel_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="tags",
            field=models.ManyToManyField(
                help_text="A list of tags associated with this release. This should NOT contain extraneous tags from Odysee -- it's a data structure specific to this site.",
                related_name="releases",
                to="odyseescraper.tag",
            ),
        ),
    ]
