# Generated by Django 5.1.5 on 2025-01-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0009_alter_odyseerelease_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseechannel",
            name="tags",
            field=models.ManyToManyField(
                help_text="A list of tags associated with this channel. When queried, any release from this channel will inherit its tags.",
                related_name="channels",
                to="odyseescraper.tag",
            ),
        ),
    ]
