# Generated by Django 5.1.5 on 2025-01-24 21:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0010_odyseechannel_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaggingRule",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for this tagging rule",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title_regex",
                    models.CharField(
                        blank=True,
                        help_text="A regular expression to match against the title of a release. If the release's title matches, the tag is applied. If this value is blank, it is ignored.",
                        max_length=512,
                    ),
                ),
                (
                    "description_regex",
                    models.CharField(
                        blank=True,
                        help_text="A regular expression to match against the description of a release. If it matches, the tag is applied. If this value is blank, it iss ignored.",
                        max_length=512,
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="The tag to assign a release with",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="odyseescraper.tag",
                    ),
                ),
            ],
        ),
    ]
