# Generated by Django 5.1.5 on 2025-01-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0011_taggingrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="taggingrule",
            name="name",
            field=models.CharField(
                default="asdf",
                help_text="A non-user-facing name for the rule",
                max_length=1024,
            ),
            preserve_default=False,
        ),
    ]
