# Generated by Django 5.1.5 on 2025-01-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0013_alter_odyseerelease_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="The name for this tag as it should be displayed across UIs",
                max_length=256,
                unique=True,
            ),
        ),
    ]
