# Generated by Django 5.1.5 on 2025-01-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0014_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taggingrule",
            name="tag",
            field=models.ForeignKey(
                help_text="The tag to assign a release with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targettag",
                to="odyseescraper.tag",
            ),
        ),
    ]
