# Generated by Django 5.1.5 on 2025-01-24 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0015_alter_taggingrule_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="taggingrule",
            name="required_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="A taga to match against a release. If this value is blank, it is ignored.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requiredtag",
                to="odyseescraper.tag",
            ),
        ),
    ]
