# Generated by Django 5.1.5 on 2025-01-24 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0016_taggingrule_required_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="taggingrule",
            name="channel_regex",
            field=models.CharField(
                blank=True,
                help_text="A regular expression to match against the channel of a release. If it matches, the tag is applied. If this value is blank, it is ignored.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="taggingrule",
            name="description_regex",
            field=models.CharField(
                blank=True,
                help_text="A regular expression to match against the description of a release. If it matches, the tag is applied. If this value is blank, it is ignored.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="taggingrule",
            name="required_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="A tag to match against a release. If this value is blank, it is ignored.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requiredtag",
                to="odyseescraper.tag",
            ),
        ),
    ]
