# Generated by Django 5.1.5 on 2025-01-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0017_taggingrule_channel_regex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseechannel",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of tags associated with this channel. When queried, any release from this channel will inherit its tags.",
                related_name="channels",
                to="odyseescraper.tag",
            ),
        ),
        migrations.AlterField(
            model_name="taggingrule",
            name="channel_regex",
            field=models.CharField(
                blank=True,
                help_text="A regular expression to match against the channel HANDLE of a release. If it matches, the tag is applied. If this value is blank, it is ignored.",
                max_length=512,
            ),
        ),
    ]
