# Generated by Django 5.1.5 on 2025-01-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0018_alter_odyseechannel_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A user-facing description of this release. This should mirror the official post from Odysee, if available",
            ),
        ),
    ]
