# Generated by Django 5.1.5 on 2025-01-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0019_alter_odyseerelease_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseechannel",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A user-facing description of the channel, its owners, and its content. May also contain links to related resources and websites.",
            ),
        ),
    ]
