# Generated by Django 5.1.5 on 2025-02-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0020_alter_odyseechannel_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="magnet",
            field=models.URLField(
                blank=True,
                help_text="A URL to a magnet link from which the content can also be accessed.",
                max_length=512,
            ),
        ),
    ]
