# Generated by Django 5.1.5 on 2025-02-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0021_odyseerelease_magnet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="magnet",
            field=models.CharField(
                blank=True,
                help_text="A URL to a magnet link from which the content can also be accessed.",
                max_length=512,
            ),
        ),
    ]
