# Generated by Django 5.1.5 on 2025-02-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0022_alter_odyseerelease_magnet"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="The RGB hex code (with #) of the color of the tag. Should contrast well with black. If unspecified, a default will be chosen",
                max_length=16,
            ),
        ),
    ]
