# Generated by Django 5.1.5 on 2025-02-16 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0023_tag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="The RGB hex code (with #) of the color of the tag. If unspecified, a default will be chosen",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message='Field must be a valid hex RGB color code prepended with "#"',
                        regex="^#(?:[0-9a-fA-F]{1,2}){3,4}$",
                    )
                ],
            ),
        ),
    ]
