# Generated by Django 5.1.6 on 2025-02-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0024_alter_tag_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="odyseechannel",
            name="tags",
        ),
    ]
