# Generated by Django 5.1.6 on 2025-02-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0025_remove_odyseechannel_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="size",
            field=models.BigIntegerField(
                default=0, help_text="The size of the release in bytes"
            ),
            preserve_default=False,
        ),
    ]
