# Generated by Django 5.1.6 on 2025-02-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0026_odyseerelease_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="odyseerelease",
            name="filehash",
        ),
    ]
