# Generated by Django 5.1.6 on 2025-02-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0027_remove_odyseerelease_filehash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseechannel",
            name="handle",
            field=models.CharField(
                help_text="The @tag of the user. May be a short tag (@someuser) or qualified with claimid (@someuser:4ab8)",
                max_length=1024,
                unique=True,
            ),
        ),
    ]
