# Generated by Django 5.1.6 on 2025-03-02 08:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0028_alter_odyseechannel_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="search_channel",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Internal. Name of the owning channel, updated on save()",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="odyseerelease",
            name="search_tag_list",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Internal. Concatenated string of all tags, updated on save()",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="odyseerelease",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="odyseerelease",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="odyseescrap_search__f0142c_gin"
            ),
        ),
    ]
