# Generated by Django 5.1.6 on 2025-03-05 00:32

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0029_odyseerelease_search_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
