# Generated by Django 5.1.6 on 2025-03-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0030_alter_odyseerelease_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="lbry_effective_amount",
            field=models.FloatField(
                default=0,
                help_text="The effective amount of the claim of this release in LBC",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="odyseerelease",
            name="lbry_reposts",
            field=models.BigIntegerField(
                default=0,
                help_text="The number of times this claim has been reposted on LBRY",
            ),
            preserve_default=False,
        ),
    ]
