# Generated by Django 5.1.6 on 2025-03-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0031_odyseerelease_lbry_effective_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Should this release be hidden from the index? Hidden releases will not show up in searches or the API",
            ),
            preserve_default=False,
        ),
    ]
