# Generated by Django 5.1.6 on 2025-03-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0032_odyseerelease_hidden"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqEntry",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_index=True,
                        help_text="The ID of this FAQ entry. All entries will be displayed in ascending order by this field.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        blank=True, help_text="The question", max_length=512
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        blank=True, help_text="The answer to the question"
                    ),
                ),
            ],
        ),
    ]
