# Generated by Django 5.1.7 on 2025-03-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0034_alter_odyseerelease_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="odyseerelease",
            name="tags",
        ),
        migrations.AddField(
            model_name="odyseerelease",
            name="manual_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of tags associated with this release. This should NOT contain extraneous tags from Odysee -- it's a data structure specific to this site.",
                related_name="releases",
                to="odyseescraper.tag",
            ),
        ),
    ]
