# Generated by Django 5.1.7 on 2025-03-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0035_remove_odyseerelease_tags_odyseerelease_manual_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="tag_rules",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                help_text="A list of TaggingRules associated with this release",
                related_name="releases",
                to="odyseescraper.taggingrule",
            ),
        ),
    ]
