# Generated by Django 5.1.7 on 2025-03-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0036_odyseerelease_tag_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="blacklisted_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of tags this release should NEVER have, even when added by TaggingRules",
                related_name="releases_blacklist",
                to="odyseescraper.tag",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="manual_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of tags manually associated with this release.",
                related_name="releases",
                to="odyseescraper.tag",
            ),
        ),
    ]
