# Generated by Django 5.1.7 on 2025-03-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0037_odyseerelease_blacklisted_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="lbry_effective_amount",
            field=models.FloatField(
                editable=False,
                help_text="The effective amount of the claim of this release in LBC",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="lbry_reposts",
            field=models.BigIntegerField(
                editable=False,
                help_text="The number of times this claim has been reposted on LBRY",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="size",
            field=models.BigIntegerField(
                editable=False, help_text="The size of the release in bytes"
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="thumbnail",
            field=models.URLField(
                editable=False,
                help_text="The URL to the Odysee-hosted thumbnail of the release",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="url",
            field=models.URLField(
                editable=False,
                help_text="The URL to the Odysee page where the release can be downloaded. It is NOT a direct download link",
                max_length=512,
            ),
        ),
    ]
