# Generated by Django 5.1.7 on 2025-03-10 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0038_alter_odyseerelease_lbry_effective_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="channel",
            field=models.ForeignKey(
                editable=False,
                help_text="The channel that this release came from",
                on_delete=django.db.models.deletion.CASCADE,
                to="odyseescraper.odyseechannel",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="description",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="A user-facing description of this release. This should mirror the official post from Odysee, if available",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="name",
            field=models.CharField(
                editable=False,
                help_text="The human-readable name of this release",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="released",
            field=models.DateField(
                editable=False, help_text="The date that this release was posted in UTC"
            ),
        ),
    ]
