# Generated by Django 5.1.7 on 2025-03-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0039_alter_odyseerelease_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of tags manually associated with this release.",
                related_name="releases_cache",
                to="odyseescraper.tag",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="manual_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of tags manually associated with this release.",
                related_name="releases_manual",
                to="odyseescraper.tag",
            ),
        ),
    ]
