# Generated by Django 5.1.7 on 2025-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0040_odyseerelease_tags_alter_odyseerelease_manual_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                help_text="A list of tags manually associated with this release.",
                related_name="releases_cache",
                to="odyseescraper.tag",
            ),
        ),
    ]
