# Generated by Django 5.1.7 on 2025-03-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0041_alter_odyseerelease_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="tag_rules",
            field=models.ManyToManyField(
                blank=True,
                help_text="A list of TaggingRules associated with this release",
                related_name="releases",
                to="odyseescraper.taggingrule",
            ),
        ),
    ]
