# Generated by Django 5.1.7 on 2025-03-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0042_alter_odyseerelease_tag_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="tag_rules",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                help_text="A list of TaggingRules associated with this release",
                related_name="releases",
                to="odyseescraper.taggingrule",
            ),
        ),
    ]
