# Generated by Django 5.1.7 on 2025-03-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0043_alter_odyseerelease_tag_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="sha384sum",
            field=models.CharField(
                default="",
                editable=False,
                help_text="The file hash of this file, in SHA384 (it's a LBRY thing don't question it)",
                max_length=256,
            ),
            preserve_default=False,
        ),
    ]
