# Generated by Django 5.1.7 on 2025-03-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0045_alter_odyseerelease_sha384sum"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseechannel",
            name="claimid",
            field=models.CharField(
                default="",
                editable=False,
                help_text="The LBRY claim ID of the channel",
                max_length=64,
            ),
        ),
    ]
