# Generated by Django 5.1.7 on 2025-03-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0046_odyseechannel_claimid"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseechannel",
            name="thumbnail",
            field=models.URLField(
                default="",
                editable=False,
                help_text="The URL to the Odysee-hosted thumbnail of the release",
                max_length=512,
            ),
        ),
    ]
