# Generated by Django 5.1.7 on 2025-03-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0047_odyseechannel_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="released",
            field=models.DateTimeField(
                editable=False, help_text="The time that this release was posted in UTC"
            ),
        ),
    ]
