# Generated by Django 5.1.7 on 2025-03-13 00:21

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0048_alter_odyseerelease_released"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagCategory",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for this category",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name for this category as it should be displayed across UIs",
                        max_length=256,
                        unique=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="The RGB hex code (with #) of all tags in the category. If unspecified, a default will be chosen",
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid",
                                message='Field must be a valid hex RGB color code prepended with "#"',
                                regex="^#(?:[0-9a-fA-F]{1,2}){3,4}$",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A user-facing description of the category"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tag",
            name="category",
            field=models.ForeignKey(
                help_text="The category to associate with this tag",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targetcategory",
                to="odyseescraper.tagcategory",
            ),
        ),
    ]
