# Generated by Django 5.1.7 on 2025-03-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0049_tagcategory_tag_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="color",
            new_name="custom_color",
        ),
    ]
