# Generated by Django 5.1.7 on 2025-03-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0050_rename_color_tag_custom_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="search_channel_handle",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Internal. Handle of the owning channel, updated on save()",
                max_length=512,
            ),
        ),
    ]
