# Generated by Django 5.1.7 on 2025-03-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0051_odyseerelease_search_channel_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="shortlink",
            field=models.CharField(
                blank=True,
                help_text="The suffix for a shortlink, e.g. guncadindex.com/<shortlink>. Max 36 characters",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
    ]
