# Generated by Django 5.1.7 on 2025-03-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0052_odyseerelease_shortlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseechannel",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Should this channel be excluded from automatic updates?",
            ),
        ),
    ]
