# Generated by Django 5.1.7 on 2025-03-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0053_odyseechannel_hidden"),
    ]

    operations = [
        migrations.RenameField(
            model_name="odyseechannel",
            old_name="hidden",
            new_name="disabled",
        ),
    ]
