# Generated by Django 5.1.7 on 2025-03-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0054_rename_hidden_odyseechannel_disabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="odyseerelease",
            name="magnet",
        ),
    ]
