# Generated by Django 5.1.7 on 2025-03-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0055_remove_odyseerelease_magnet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="shortlink",
            field=models.CharField(
                blank=True,
                help_text="A custom slug for a shortlink which will be made available at guncadindex.com/s/<shortlink>. Use sparingly",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
    ]
