# Generated by Django 5.1.7 on 2025-03-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0056_alter_odyseerelease_shortlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="url_lbry",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The URL to the LBRY claim for this release.",
                max_length=512,
            ),
        ),
    ]
