# Generated by Django 5.1.7 on 2025-03-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0057_odyseerelease_url_lbry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="released",
            field=models.DateTimeField(
                db_index=True,
                editable=False,
                help_text="The time that this release was posted in UTC",
            ),
        ),
    ]
