# Generated by Django 5.1.7 on 2025-03-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0059_alter_odyseerelease_sha384sum"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="duplicate",
            field=models.BooleanField(
                db_index=True,
                default=False,
                editable=False,
                help_text="Is this release a duplicate of another in the index? Functions as hidden",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="hidden",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Should this release be hidden from the index? Hidden releases will not show up in searches or the API",
            ),
        ),
    ]
