# Generated by Django 5.1.7 on 2025-03-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0060_odyseerelease_duplicate_alter_odyseerelease_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="odyseerelease",
            name="duplicate",
        ),
    ]
