# Generated by Django 5.1.7 on 2025-03-29 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0061_remove_odyseerelease_duplicate"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="duplicate",
            field=models.ForeignKey(
                default=None,
                editable=False,
                help_text="If this file is a duplicate, this is the release it's a duplicate of",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="release_duplicate",
                to="odyseescraper.odyseerelease",
            ),
        ),
    ]
