# Generated by Django 5.1.7 on 2025-03-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0062_odyseerelease_duplicate"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="The slug for this tag", max_length=64, null=True, unique=True
            ),
        ),
    ]
