# Generated by Django 5.1.7 on 2025-04-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0063_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                editable=False,
                help_text="The slug for this tag",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
