# Generated by Django 5.1.7 on 2025-04-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0064_alter_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="slug",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The short_url of the object, which is the shortest possible resolvable name the claim can sit under.",
                max_length=512,
            ),
        ),
    ]
