# Generated by Django 5.1.8 on 2025-04-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0065_odyseerelease_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="odyseerelease",
            name="slug",
        ),
    ]
