# Generated by Django 5.1.8 on 2025-04-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0066_remove_odyseerelease_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="slug",
            field=models.CharField(
                editable=False,
                help_text="The short_url of the object, which is the shortest possible resolvable name the claim can sit under.",
                max_length=512,
                null=True,
                unique=True,
            ),
        ),
    ]
