# Generated by Django 5.1.8 on 2025-04-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0067_odyseerelease_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="sd_hash",
            field=models.CharField(
                db_index=True,
                default="",
                editable=False,
                help_text="The sd_hash of the file, representing the blob which describes the rest of the file.",
                max_length=256,
            ),
        ),
    ]
