# Generated by Django 5.1.8 on 2025-04-17 02:09

import datetime

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0068_odyseerelease_sd_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="last_updated",
            field=models.DateTimeField(
                db_index=True,
                default=timezone.now,
                editable=False,
                help_text="The time that this release was last updated in UTC",
            ),
        ),
    ]
