# Generated by Django 5.1.8 on 2025-04-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0069_odyseerelease_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="last_updated",
            field=models.DateTimeField(
                db_index=True,
                editable=False,
                help_text="The time that this release was last updated in UTC",
            ),
        ),
    ]
