# Generated by Django 5.1.8 on 2025-04-17 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0070_alter_odyseerelease_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="odyseerelease",
            name="last_updated",
        ),
    ]
