# Generated by Django 5.1.8 on 2025-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0072_odyseerelease_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="abandoned",
            field=models.BooleanField(
                db_index=True,
                default=False,
                editable=False,
                help_text="Has this release had its support withdrawn by its author? This results in complete inaccessibility of the release",
            ),
        ),
    ]
