# Generated by Django 5.1.8 on 2025-04-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0073_odyseerelease_abandoned"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="ai_tags",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                help_text="A list of tags the linked LLM thinks this release should have.",
                related_name="releases_ai",
                to="odyseescraper.tag",
            ),
        ),
    ]
