# Generated by Django 5.1.8 on 2025-04-30 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0074_odyseerelease_ai_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faqentry",
            options={"verbose_name": "FAQ entry", "verbose_name_plural": "FAQ entries"},
        ),
        migrations.AlterModelOptions(
            name="odyseechannel",
            options={
                "verbose_name": "Odysee channel",
                "verbose_name_plural": "Odysee channels",
            },
        ),
        migrations.AlterModelOptions(
            name="odyseerelease",
            options={
                "verbose_name": "Odysee release",
                "verbose_name_plural": "Odysee releases",
            },
        ),
        migrations.AlterModelOptions(
            name="tagcategory",
            options={
                "verbose_name": "tag category",
                "verbose_name_plural": "tag categories",
            },
        ),
        migrations.AlterModelOptions(
            name="taggingrule",
            options={
                "verbose_name": "tagging rule",
                "verbose_name_plural": "tagging rules",
            },
        ),
        migrations.AlterField(
            model_name="odyseechannel",
            name="claimid",
            field=models.CharField(
                default="",
                editable=False,
                help_text="The LBRY claim ID of the channel",
                max_length=64,
                verbose_name="claim ID",
            ),
        ),
        migrations.AlterField(
            model_name="odyseechannel",
            name="thumbnail",
            field=models.URLField(
                default="",
                editable=False,
                help_text="The URL to the Odysee-hosted thumbnail of the channel",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="taggingrule",
            name="channel_regex",
            field=models.CharField(
                blank=True,
                help_text="A regular expression to match against the channel HANDLE of a release. If it matches, the tag is applied. If this value is blank, it is ignored.",
                max_length=512,
                verbose_name="channel handle regex",
            ),
        ),
        migrations.AlterField(
            model_name="taggingrule",
            name="tag",
            field=models.ForeignKey(
                help_text="The tag to assign a release with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targettag",
                to="odyseescraper.tag",
                verbose_name="assigned tag",
            ),
        ),
    ]
