# Generated by Django 5.1.8 on 2025-04-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "odyseescraper",
            "0075_alter_faqentry_options_alter_odyseechannel_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseechannel",
            name="lbry_only",
            field=models.BooleanField(
                default=False,
                help_text='Is this channel only navigable via LBRY? Usually only applicable to channels marked "mature"',
                verbose_name="LBRY only",
            ),
        ),
        migrations.AddField(
            model_name="odyseerelease",
            name="lbry_only",
            field=models.BooleanField(
                default=False,
                help_text="Is this release only navigable via LBRY? Can be a result of a lot of things, like unlisting from Odysee",
                verbose_name="LBRY only",
            ),
        ),
    ]
