# Generated by Django 5.1.8 on 2025-05-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0076_odyseechannel_lbry_only_odyseerelease_lbry_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="release_state",
            field=models.IntegerField(
                choices=[
                    (-1, "Beta"),
                    (0, "Released"),
                    (1, "Verified"),
                    (5, "Superverified"),
                ],
                default=0,
                help_text="What state of release is this item in?",
            ),
        ),
    ]
