# Generated by Django 5.1.8 on 2025-05-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0077_odyseerelease_release_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseechannel",
            name="default_release_state",
            field=models.IntegerField(
                choices=[
                    (-1, "Beta"),
                    (0, "Released"),
                    (1, "Verified"),
                    (5, "Superverified"),
                ],
                default=0,
                help_text="What state of release should we assign to this channel?",
            ),
        ),
    ]
