# Generated by Django 5.1.8 on 2025-05-01 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0078_odyseechannel_default_release_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="odyseerelease",
            name="release_state",
        ),
    ]
