# Generated by Django 5.1.8 on 2025-05-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0081_alter_odyseerelease_release_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseechannel",
            name="default_release_state",
            field=models.IntegerField(
                choices=[
                    (-10, "Unsafe"),
                    (-1, "Beta"),
                    (0, "Released"),
                    (1, "Verified"),
                    (5, "Superverified"),
                ],
                default=0,
                help_text="What state of release should we assign to this channel?",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="release_state",
            field=models.IntegerField(
                choices=[
                    (-10, "Unsafe"),
                    (-1, "Beta"),
                    (0, "Released"),
                    (1, "Verified"),
                    (5, "Superverified"),
                ],
                help_text="What state of release is this item in? If unset, defaults to the channel's default release state.",
                null=True,
            ),
        ),
    ]
