# Generated by Django 5.1.8 on 2025-05-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0082_alter_odyseechannel_default_release_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseechannel",
            name="default_release_state",
            field=models.IntegerField(
                choices=[(0, "Released"), (1, "Verified")],
                default=0,
                help_text="What state of release should we assign to this channel?",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="release_state",
            field=models.IntegerField(
                choices=[(0, "Released"), (1, "Verified")],
                help_text="What state of release is this item in? If unset, defaults to the channel's default release state.",
                null=True,
            ),
        ),
    ]
