# Generated by Django 5.1.9 on 2025-05-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0084_alter_odyseerelease_release_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="lbry_support_amount",
            field=models.FloatField(
                default=0,
                editable=False,
                help_text="The effective amount of the claim of this release in LBC",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="lbry_effective_amount",
            field=models.FloatField(
                default=0,
                editable=False,
                help_text="The effective amount of the claim of this release in LBC",
            ),
        ),
    ]
