# Generated by Django 5.1.9 on 2025-05-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0085_odyseerelease_lbry_support_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="lbry_effective_amount",
            field=models.FloatField(
                default=0,
                editable=False,
                help_text="The effective amount of the claim of this release in LBC",
                verbose_name="LBRY effective amount",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="lbry_reposts",
            field=models.BigIntegerField(
                editable=False,
                help_text="The number of times this claim has been reposted on LBRY",
                verbose_name="LBRY reposts",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="lbry_support_amount",
            field=models.FloatField(
                default=0,
                editable=False,
                help_text="The subset of the effective amount that was community-contributed in LBC",
                verbose_name="LBRY support amount",
            ),
        ),
    ]
