# Generated by Django 5.1.9 on 2025-06-01 02:54

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0086_alter_odyseerelease_lbry_effective_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="similarity_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
