# Generated by Django 5.1.9 on 2025-06-01 02:58

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0087_odyseerelease_similarity_vector"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="odyseerelease",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["similarity_vector"], name="odyseescrap_similar_b0e914_gin"
            ),
        ),
    ]
