# Generated by Django 5.1.9 on 2025-06-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0088_odyseerelease_odyseescrap_similar_b0e914_gin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="lbry_effective_amount",
            field=models.FloatField(
                db_index=True,
                default=0,
                editable=False,
                help_text="The effective amount of the claim of this release in LBC",
                verbose_name="LBRY effective amount",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="lbry_reposts",
            field=models.BigIntegerField(
                db_index=True,
                editable=False,
                help_text="The number of times this claim has been reposted on LBRY",
                verbose_name="LBRY reposts",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="lbry_support_amount",
            field=models.FloatField(
                db_index=True,
                default=0,
                editable=False,
                help_text="The subset of the effective amount that was community-contributed in LBC",
                verbose_name="LBRY support amount",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="release_state",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Released"), (1, "Verified")],
                db_index=True,
                help_text="What state of release is this item in? If unset, defaults to the channel's default release state.",
                null=True,
            ),
        ),
    ]
