# Generated by Django 5.1.9 on 2025-06-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0089_alter_odyseerelease_lbry_effective_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="popularity",
            field=models.IntegerField(
                db_index=True,
                default=1,
                editable=False,
                help_text="What is the ranking factor of this release? This field is automatically calculated based on a number of statistics about this release.",
            ),
        ),
    ]
