# Generated by Django 5.1.9 on 2025-06-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0090_odyseerelease_popularity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseerelease",
            name="popularity",
            field=models.FloatField(
                db_index=True,
                default=1.0,
                editable=False,
                help_text="What is the ranking factor of this release? This field is automatically calculated based on a number of statistics about this release.",
            ),
        ),
    ]
