# Generated by Django 5.1.9 on 2025-06-01 04:54

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("odyseescraper", "0093_manual_add_trgm_extension")]

    operations = [
        migrations.AddIndex(
            model_name="odyseerelease",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="odyseerelease_trgm_ops",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
