# Generated by Django 5.1.10 on 2025-06-10 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("odyseescraper", "0092_odyseerelease_odyseerelease_trgm_ops")]

    operations = [
        migrations.AddField(
            model_name="odyseechannel",
            name="discovered",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="The time that this channel was added",
            ),
        ),
    ]
