# Generated by Django 5.1.11 on 2025-06-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0094_odyseechannel_discovered"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="odysee_dislikes",
            field=models.BigIntegerField(
                default=0,
                editable=False,
                help_text='The number of "slimes" (dislikes) this release has on Odysee',
                verbose_name="Odysee slimes",
            ),
        ),
        migrations.AddField(
            model_name="odyseerelease",
            name="odysee_likes",
            field=models.BigIntegerField(
                default=0,
                editable=False,
                help_text="The number of likes this release has on Odysee",
                verbose_name="Odysee likes",
            ),
        ),
        migrations.AddField(
            model_name="odyseerelease",
            name="odysee_views",
            field=models.BigIntegerField(
                default=0,
                editable=False,
                help_text="The number of views this release has on Odysee",
                verbose_name="Odysee views",
            ),
        ),
    ]
