# Generated by Django 5.1.11 on 2025-06-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0095_odyseerelease_odysee_dislikes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="odysee_last_updated",
            field=models.DateTimeField(
                editable=False,
                help_text="The last time that this model had its Odysee statistics updated",
                null=True,
            ),
        ),
    ]
