# Generated by Django 5.1.11 on 2025-06-25 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0096_odyseerelease_odysee_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="discovered",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="The date this release was discovered",
            ),
        ),
    ]
