# Generated by Django 5.1.11 on 2025-06-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0097_odyseerelease_discovered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseechannel",
            name="default_release_state",
            field=models.IntegerField(
                choices=[(-2, "Dangerous"), (0, "Released"), (1, "Verified")],
                default=0,
                help_text="What state of release should we assign to this channel?",
            ),
        ),
        migrations.AlterField(
            model_name="odyseerelease",
            name="release_state",
            field=models.IntegerField(
                blank=True,
                choices=[(-2, "Dangerous"), (0, "Released"), (1, "Verified")],
                db_index=True,
                help_text="What state of release is this item in? If unset, defaults to the channel's default release state.",
                null=True,
            ),
        ),
    ]
