# Generated by Django 5.1.11 on 2025-07-02 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0098_alter_odyseechannel_default_release_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taggingrule",
            name="required_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="A tag to match against a release. If this value is blank, it is ignored.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_by",
                to="odyseescraper.tag",
            ),
        ),
        migrations.AlterField(
            model_name="taggingrule",
            name="tag",
            field=models.ForeignKey(
                help_text="The tag to assign a release with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targeted_by",
                to="odyseescraper.tag",
                verbose_name="assigned tag",
            ),
        ),
    ]
