# Generated by Django 5.1.11 on 2025-07-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0099_alter_taggingrule_required_tag_alter_taggingrule_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="license",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The license this release is under",
                max_length=1024,
            ),
        ),
    ]
