# Generated by Django 5.1.11 on 2025-07-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0100_odyseerelease_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="taggingrule",
            name="license_regex",
            field=models.CharField(
                blank=True,
                help_text="A regular expression to match against the license field of a release. If it matches, the tag is applied. If this value is blank, it is ignored.",
                max_length=512,
                verbose_name="channel handle regex",
            ),
        ),
    ]
