# Generated by Django 5.1.11 on 2025-07-17 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0102_odyseereleasethumbnail"),
        ("releases", "0009_channel_release_channel_channelthumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="OdyseeChannelThumbnail",
            fields=[
                (
                    "thumbnail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="releases.thumbnail",
                    ),
                ),
                (
                    "release",
                    models.OneToOneField(
                        help_text="The release this thumbnail represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnail_manager",
                        to="odyseescraper.odyseechannel",
                    ),
                ),
            ],
            bases=("releases.thumbnail",),
        ),
    ]
