# Generated by Django 5.1.11 on 2025-08-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0103_odyseechannelthumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="odyseerelease",
            name="uniqueness",
            field=models.FloatField(
                db_index=True,
                default=0.0,
                editable=False,
                help_text="How unique is this release? This is evaluated elsewhere in a management command based on factors like tag rarity",
            ),
        ),
    ]
