# Generated by Django 5.1.11 on 2025-08-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0104_odyseerelease_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagcategory",
            name="useforweighting",
            field=models.BooleanField(
                default=True,
                help_text="Should tags in this category be used for things like search and uniqueness weighting?",
                verbose_name="use for weighting",
            ),
        ),
    ]
