# Generated by Django 5.1.12 on 2025-09-13 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0105_tagcategory_useforweighting"),
    ]

    operations = [
        migrations.CreateModel(
            name="OdyseeReleaseSimilar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="The time that this model was last updated. If this date is in the future, the model has a backoff timer set",
                    ),
                ),
                (
                    "release",
                    models.OneToOneField(
                        help_text="The release this similarity manager represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_manager",
                        to="odyseescraper.odyseerelease",
                    ),
                ),
                (
                    "similar",
                    models.ManyToManyField(
                        help_text="The releases this release is similar to",
                        related_name="similar_to",
                        to="odyseescraper.odyseerelease",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
