# Generated by Django 5.1.12 on 2025-09-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0106_odyseereleasesimilar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="odyseereleasesimilar",
            options={
                "verbose_name": "Odysee release similarity manager",
                "verbose_name_plural": "Odysee release similarity managers",
            },
        ),
    ]
