# Generated by Django 5.1.12 on 2025-09-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0107_alter_odyseereleasesimilar_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odyseereleasesimilar",
            name="similar",
            field=models.ManyToManyField(
                blank=True,
                help_text="The releases this release is similar to",
                related_name="similar_to",
                to="odyseescraper.odyseerelease",
            ),
        ),
    ]
