# Generated by Django 5.1.13 on 2025-10-24 21:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0108_alter_odyseereleasesimilar_similar"),
    ]

    operations = [
        migrations.CreateModel(
            name="OdyseeReleaseLemmy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="The time that this model was last updated. If this date is in the future, the model has a backoff timer set",
                    ),
                ),
                (
                    "search_results",
                    models.JSONField(
                        help_text="The results of a search for the associated release",
                        null=True,
                    ),
                ),
                (
                    "release",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lemmy_manager",
                        to="odyseescraper.odyseerelease",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
