# Generated by Django 5.1.13 on 2025-10-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odyseescraper", "0109_odyseereleaselemmy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="odyseereleaselemmy",
            options={
                "verbose_name": "Odysee release lemmy manager",
                "verbose_name_plural": "Odysee release lemmy managers",
            },
        ),
    ]
