# Generated by Django 5.1.7 on 2025-03-13 06:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("odyseescraper", "0050_rename_color_tag_custom_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagVote",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for this TagEdit",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "voter",
                    models.CharField(
                        editable=False,
                        help_text="The hash of the IP of the user who submitted this vote",
                        max_length=128,
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        choices=[(1, "Upvote"), (-1, "Downvote")],
                        editable=False,
                        help_text="The value of this particular vote",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        editable=False,
                        help_text="The OdyseeRelease this edit intends to modify",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votedrelease",
                        to="odyseescraper.odyseerelease",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        editable=False,
                        help_text="The Tag this edit intends to either append or remove",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votedtag",
                        to="odyseescraper.tag",
                    ),
                ),
            ],
        ),
    ]
