# Generated by Django 5.1.7 on 2025-03-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsource", "0001_initial"),
        ("odyseescraper", "0050_rename_color_tag_custom_color"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tagvote",
            unique_together={("voter", "release", "tag")},
        ),
    ]
