# Generated by Django 5.1.8 on 2025-04-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsource", "0002_alter_tagvote_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tagvote",
            options={"verbose_name": "tag vote", "verbose_name_plural": "tag votes"},
        ),
    ]
