# Generated by Django 5.1.11 on 2025-08-08 16:27

import uuid

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsource", "0003_alter_tagvote_options"),
        ("odyseescraper", "0105_tagcategory_useforweighting"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagSuggestion",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for this TagEdit",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.IntegerField(
                        choices=[(1, "Human"), (2, "Ai")],
                        editable=False,
                        help_text="Where this suggestion came from",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        editable=False,
                        help_text="The name of the tag that should be added",
                        max_length=128,
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        editable=False,
                        help_text="The OdyseeRelease this suggestion is intended for",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_tag",
                        to="odyseescraper.odyseerelease",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag suggestion",
                "verbose_name_plural": "tag suggestions",
                "unique_together": {("tag", "release")},
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("tagsuggestion"),
                models.Model,
            ),
        ),
    ]
