# Generated by Django 5.1.11 on 2025-08-08 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsource", "0004_tagsuggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagsuggestion",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this suggestion was made",
            ),
        ),
    ]
