# Generated by Django 5.1.11 on 2025-08-08 16:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsource", "0005_tagsuggestion_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagsuggestion",
            name="id",
            field=models.CharField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="A unique identifier for this TagSuggestion",
                max_length=512,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
