# Generated by Django 5.1.13 on 2025-10-17 17:50

import uuid

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsource", "0006_alter_tagsuggestion_id"),
        ("odyseescraper", "0108_alter_odyseereleasesimilar_similar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for this report",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "voter",
                    models.CharField(
                        editable=False,
                        help_text="The hash of the IP of the user who submitted this report",
                        max_length=128,
                    ),
                ),
                (
                    "reason_index",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Not GunCAD-related"),
                            (1, "Copyright or other IP infringement"),
                            (2, "Malicious content (malware, etc.)"),
                            (3, "Misleading content (named inaccurately, etc.)"),
                            (4, "Other"),
                        ],
                        help_text="Index of the reason for reporting",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        editable=False,
                        help_text="The OdyseeRelease this edit intends to modify",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="odyseescraper.odyseerelease",
                    ),
                ),
            ],
            options={
                "verbose_name": "report",
                "verbose_name_plural": "reports",
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("report"),
                models.Model,
            ),
        ),
    ]
