# Generated by Django 5.1.13 on 2025-10-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdsource", "0007_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reason_index",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Not GunCAD-related"),
                    (1, "Copyright or other IP infringement"),
                    (2, "It's mine and I want it taken down"),
                    (3, "Malicious content"),
                    (4, "Misleading content"),
                    (5, "Other"),
                ],
                help_text="Index of the reason for reporting",
            ),
        ),
    ]
