# Generated by Django 5.1.11 on 2025-06-26 06:06

import uuid

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminSiteBanner",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for this banner",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=False,
                        help_text="Should this banner be visible below the navbar?",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="The contents of the text of this banner. Can contain HTML",
                        max_length=1024,
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("banner"),
                models.Model,
            ),
        ),
    ]
