# Generated by Django 5.1.11 on 2025-06-26 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admintools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminsitebanner",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="The RGB hex code (with #) of the color of the banner. If unspecified, a default will be chosen",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message='Field must be a valid hex RGB color code prepended with "#"',
                        regex="^#(?:[0-9a-fA-F]{1,2}){3,4}$",
                    )
                ],
            ),
        ),
    ]
