# Generated by Django 5.1.11 on 2025-06-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admintools", "0002_adminsitebanner_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminsitebanner",
            name="text",
            field=models.TextField(
                help_text="The contents of the text of this banner. Can contain HTML"
            ),
        ),
    ]
