# Generated by Django 5.1.11 on 2025-06-26 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admintools", "0003_alter_adminsitebanner_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminsitebanner",
            options={
                "verbose_name": "sitewide banner",
                "verbose_name_plural": "sitewide banners",
            },
        ),
        migrations.AddField(
            model_name="adminsitebanner",
            name="priority",
            field=models.IntegerField(
                db_index=True,
                default=1000,
                help_text="Higher numbers are higher up in the list of sitewide banners",
            ),
        ),
        migrations.AlterField(
            model_name="adminsitebanner",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="The RGB hex code (with #) of the color of the banner. If unspecified, a default will be chosen",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message='Field must be a valid hex RGB color code prepended with "#"',
                        regex="^#(?:[0-9a-fA-F]{2}){3,4}$",
                    )
                ],
            ),
        ),
    ]
