# Generated by Django 5.1.12 on 2025-09-27 18:26

import uuid

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admintools", "0004_alter_adminsitebanner_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNavbarLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for this navbar link",
                        max_length=512,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=1000,
                        help_text="Higher numbers are higher up in the list of navbar links",
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=False,
                        help_text="Should this link be visible in the navbar?",
                    ),
                ),
                (
                    "newtab",
                    models.BooleanField(
                        default=False, help_text="Should this link open in a new tab?"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="The title of this navbar", max_length=128
                    ),
                ),
                (
                    "link",
                    models.CharField(help_text="Where this navbar link should go to"),
                ),
                (
                    "css_class",
                    models.CharField(
                        blank=True,
                        help_text="Any additional classes this link should have",
                        max_length=256,
                    ),
                ),
            ],
            options={
                "verbose_name": "navbar link",
                "verbose_name_plural": "navbar links",
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("navbarlink"),
                models.Model,
            ),
        ),
    ]
