# Generated by Django 5.1.9 on 2025-05-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrafficClassifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("user_agent", "User Agent"),
                            ("host", "Host Header"),
                            ("xff", "X-Forwarded-For IP"),
                        ],
                        default="user_agent",
                        help_text="The field this traffic classifier should act on",
                        max_length=20,
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="The regex pattern of this traffic classifier rule. Be very careful with complicated regex expressions",
                        max_length=255,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="audience", help_text="The label to set", max_length=50
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        default="human",
                        help_text="The value to set label to",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="A freshly-created rule",
                        help_text="An admin-facing description of this traffic classifier rule",
                    ),
                ),
            ],
        ),
    ]
