# Generated by Django 5.1.9 on 2025-05-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficclassifier",
            name="description",
            field=models.TextField(
                blank=True,
                default="Traffic Rule",
                help_text="An admin-facing description of this traffic classifier rule",
            ),
        ),
    ]
