# Generated by Django 5.1.9 on 2025-05-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_alter_trafficclassifier_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trafficclassifier",
            name="label",
        ),
        migrations.AlterField(
            model_name="trafficclassifier",
            name="value",
            field=models.CharField(
                default="human",
                help_text="The value to tag this request with",
                max_length=50,
            ),
        ),
    ]
