# Generated by Django 5.1.9 on 2025-05-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_remove_trafficclassifier_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficclassifier",
            name="pattern",
            field=models.CharField(
                help_text="The substring pattern of this traffic classifier rule",
                max_length=255,
            ),
        ),
    ]
