# Generated by Django 5.1.9 on 2025-05-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0004_alter_trafficclassifier_pattern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficclassifier",
            name="value",
            field=models.CharField(
                default="human",
                help_text='The value to tag this request with. Requests that don\'t match any of these rules will be tagged as "human"',
                max_length=50,
            ),
        ),
    ]
