# Generated by Django 5.1.9 on 2025-05-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0005_alter_trafficclassifier_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficclassifier",
            name="priority",
            field=models.IntegerField(
                default=100,
                help_text="The priority of this rule. Higher-priority rules are processed first",
            ),
        ),
    ]
