# Generated by Django 5.1.9 on 2025-05-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0006_trafficclassifier_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficclassifier",
            name="description",
            field=models.TextField(
                default="Unnamed Traffic Rule",
                help_text="An admin-facing description of this traffic classifier rule",
            ),
        ),
    ]
