# Generated by Django 5.1.9 on 2025-06-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0007_alter_trafficclassifier_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficclassifier",
            name="kind",
            field=models.CharField(
                choices=[
                    ("user_agent", "User Agent"),
                    ("referrer", "Referrer Header"),
                    ("host", "Host Header"),
                    ("xff", "X-Forwarded-For IP"),
                    ("path", "Request Path"),
                ],
                default="user_agent",
                help_text="The field this traffic classifier should act on",
                max_length=20,
            ),
        ),
    ]
