# Generated by Django 5.1.13 on 2025-10-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0008_alter_trafficclassifier_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficclassifier",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text="The substring pattern of this traffic classifier rule",
                max_length=255,
            ),
        ),
    ]
