# Generated by Django 5.1.13 on 2025-10-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0009_alter_trafficclassifier_pattern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficclassifier",
            name="pattern",
            field=models.CharField(
                blank=True,
                help_text='The substring pattern of this traffic classifier rule. Special string ":empty:" will match empty strings',
                max_length=255,
            ),
        ),
    ]
