#
# GunCAD Index Docker Compose
# docker-compose-dev.yml
#
# This Docker Compose file builds the containers, but then *mounts in* the git
# repository under /app, allowing for Gunicorn hot-reloads. It's the best
# option for local development work
#
# DO NOT use this for production under ANY circumstances.
#
---
name: guncad-index
version: "3.8"
services:
  guncad-index:
    build: ../guncadindex
    env_file: test-guncad-index.env
    environment:
      - GUNCAD_AI_XAI_API_KEY=${GUNCAD_AI_XAI_API_KEY}
    command:
      - gunicorn
    volumes:
      - ../guncadindex/:/app:z
      - gci-data:/data:z
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test: curl -A "HealthCheck" -f http://127.0.0.100:8080/healthz || exit 1
      interval: 5s
      timeout: 15s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gci-private
  cron:
    build: ../guncadindex
    env_file: test-guncad-index.env
    command:
      - cron
    volumes:
      - ../guncadindex/:/app:z
      - gci-data:/data:z
    depends_on:
      db:
        condition: service_healthy
      guncad-index:
        condition: service_healthy
      lbrynet:
        condition: service_healthy
    networks:
      - gci-private
  lbrynet:
    build: ../guncadindex
    env_file: test-guncad-index.env
    command:
      - lbrynet
    volumes:
      - gci-lbry-data:/home/django/.local/share/lbry:Z
    healthcheck:
      test: |
        curl -f http://127.0.0.1:5279 -X POST -d '{"method": "status"}' | grep -ie '^.*is_running.*true.*$' || exit 1
      start_period: 300s
      interval: 5s
      timeout: 15s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    networks:
      gci-private:
        aliases:
          - lbrynet
  db:
    image: docker.io/postgres:17
    env_file: test-postgres.env
    volumes:
      - gci-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U django -d django
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - gci-private
  valkey:
    image: docker.io/valkey/valkey:8-alpine
    networks:
      gci-private:
        aliases:
          - valkey
  statsd-exporter:
    # The statsd exporter here is completely optional, but is recommended for
    # observability. You can also use statsd-native tooling, but I like
    # Prometheus' stack more, personally.
    image: docker.io/prom/statsd-exporter:v0.22.4
    ports:
      - "9102:9102"
    command:
      - --statsd.mapping-config=/statsd/statsd.conf
    volumes:
      - ./contrib/statsd-exporter.conf:/statsd/statsd.conf:z
    networks:
      gci-private:
        aliases:
          - statsd-exporter
networks:
  gci-private:
volumes:
  gci-pgdata:
  gci-data:
  gci-lbry-data:
