#
# Example GunCAD Index nginx.conf
# Used in the docker-compose.yml file
#
# Should be good for most setups. Does NOT include certbot.
#
worker_processes  1;
events {
	worker_connections  2048;
}
http {
	include				mime.types;
	default_type 			application/octet-stream;
	keepalive_timeout		65;
	upstream gunicorn {
		# The Index, basically
		server guncad-index:8080;
	}
	server {
		listen 80;
		server_name _;
		location /static/ {
			alias		/data/static/;
			access_log	off;
			expires		1w;
			add_header	Cache-Control "public, max-age=31536000, immutable";
			sendfile	on;
			tcp_nopush	on;
			tcp_nodelay	on;
		}
		location /media/ {
			alias		/data/media/;
			access_log	off;
			expires		1w;
			add_header	Cache-Control "public, max-age=3600, immutable";
			sendfile	on;
			tcp_nopush	on;
			tcp_nodelay	on;
		}
		location / {
			proxy_set_header	Host			$host;
			proxy_set_header	X-Real-IP		$remote_addr;
			proxy_set_header	X-Forwarded-For		$proxy_add_x_forwarded_for;
			proxy_set_header	X-Forwarded-Proto	$scheme;
			# Consider adding this line if you hook Tor up
			# Note that there should be NO slash between the .onion and $request_uri
			#add_header Onion-Location "http://[MY TOR ONION DOMAIN]$request_uri" always;
			proxy_pass http://gunicorn;
			proxy_redirect off;
		}
	}
}
