---
mappings:
  - match: "*.gunicorn.request.status.*"
    help: "Number of responses Gunicorn gives out, broken out by response code"
    name: "gunicorn_response_code"
    labels:
      app: "$1"
      status: "$2"
      status_class: "${2:0:1}xx"
  - match: "*.gunicorn.workers"
    help: "Number of live Gunicorn workers"
    name: "gunicorn_workers"
    labels:
      app: "$1"
  - match: "*.gunicorn.requests"
    help: "Number of Gunicorn requests"
    name: "gunicorn_requests"
    labels:
      app: "$1"
  - match: "*.gunicorn.request.duration"
    help: "Duration of Gunicorn requests"
    name: "gunicorn_request_duration"
    labels:
      app: "$1"
