# Generated by Django 6.0.2 on 2026-02-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cuck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="The region string to match against",
                        max_length=8,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        default="No reason given",
                        help_text="The reason to display on the block page",
                    ),
                ),
            ],
        ),
    ]
