# Generated by Django 6.0.3 on 2026-03-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cf", "0003_alter_cuck_disabled_alter_cuck_valid_after"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuck",
            name="action",
            field=models.IntegerField(
                choices=[(50, "Restrict Access Heavy"), (100, "Block")],
                default=100,
                help_text="What should we do for users in this region?",
            ),
        ),
    ]
