#
# GunCAD Index Docker Compose
# docker-compose.yml
#
# This Docker Compose file pulls images from the canonical GitLab image
# registry instead of building locally. It's the best first-stop for running
# your own production instance
#
# Copy .env-template to .env and edit its values before you bring the stack up
#
---
name: guncad-index-prod
version: "3.8"
services:
  nginx:
    # The nginx container in front
    # Serves web requests, proxies connections to Gunicorn, manages statics
    image: nginx:latest
    env_file: .env
    volumes:
      - ./contrib/nginx.conf:/etc/nginx/nginx.conf:ro
      - gci-static:/data/static:ro
      - gci-media:/data/media:ro
    healthcheck:
      test: curl -A "HealthCheck" -f http://127.0.0.1:80 || exit 1
      interval: 5s
      timeout: 15s
      retries: 3
    ports:
      - 0.0.0.0:8265:80
    depends_on:
      guncad-index:
        condition: service_healthy
    networks:
      - gci-private
  guncad-index:
    # The GunCAD Index's gunicorn container
    # Serves rendered web requests
    image: registry.gitlab.com/guncad-index/index:latest
    env_file: .env
    command:
      - gunicorn
    volumes:
      - gci-static:/data/static:z
      - gci-media:/data/media:z
    healthcheck:
      test: curl -A "HealthCheck" -f http://127.0.0.100:8080/healthz || exit 1
      interval: 5s
      timeout: 15s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gci-private
  cron:
    # The GunCAD Index's cron container
    # Is responsible for spidering, scraping, and other background jobs
    image: registry.gitlab.com/guncad-index/index:latest
    env_file: .env
    command:
      - cron
    volumes:
      - gci-static:/data/static:z
      - gci-media:/data/media:z
    depends_on:
      db:
        condition: service_healthy
      guncad-index:
        condition: service_healthy
      lbrynet:
        condition: service_healthy
    networks:
      - gci-private
  lbrynet:
    # LBRYnet
    # Our portal into LBRY/Odysee
    image: registry.gitlab.com/guncad-index/index:latest
    env_file: .env
    command:
      - lbrynet
    volumes:
      - gci-lbry-data:/home/django/.local/share/lbry:Z
    healthcheck:
      test: |
        curl -f http://127.0.0.1:5279 -X POST -d '{"method": "status"}' | grep -ie '^.*is_running.*true.*$' || exit 1
      start_period: 300s
      interval: 5s
      timeout: 15s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    networks:
      gci-private:
        aliases:
          - lbrynet
  db:
    # PostgreSQL
    # Backing database
    image: docker.io/postgres:17
    env_file: .env
    volumes:
      - gci-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U django -d guncad-index
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - gci-private
  valkey:
    # Valkey
    # Cache. Required for a lot of things
    image: docker.io/valkey/valkey:8-alpine
    networks:
      gci-private:
        aliases:
          - valkey
  statsd-exporter:
    # The statsd exporter here is completely optional, but is recommended for
    # observability. You can also use statsd-native tooling, but I like
    # Prometheus' stack more, personally.
    image: docker.io/prom/statsd-exporter:v0.22.4
    ports:
      - "9102:9102"
    command:
      - --statsd.mapping-config=/statsd/statsd.conf
    volumes:
      - ./contrib/statsd-exporter.conf:/statsd/statsd.conf:z
    networks:
      gci-private:
        aliases:
          - statsd-exporter
networks:
  gci-private:
volumes:
  gci-pgdata:  # Volume for the PostgreSQL database
  gci-static:  # Volume for Django static files, must be shared with nginx
  gci-media:  # Volume for Django media files, must be shared with nginx
  gci-lbry-data:  # Volume for LBRY blockchain data. Can be cleared if you really need to
