# Generated by Django 5.1.8 on 2025-04-18 20:51

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "disabled",
                    models.BooleanField(
                        default=False, help_text="Should this vendor be hidden?"
                    ),
                ),
                (
                    "should_markup",
                    models.BooleanField(
                        default=False,
                        help_text="NYI. Determines whether links to this vendor in descriptions of posts should be marked up richly in release detail views.",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique identifier for this vendor",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='The friendly name of this vendor (ex. "Velocity Arms")',
                        max_length=256,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A user-facing description of this vendor. Should include a brief synopsis of who they are and the services they offer."
                    ),
                ),
                (
                    "domains",
                    models.CharField(
                        blank=True,
                        help_text="A semicolon-separated (;) list of domains (not to be confused with URLs) this vendor is responsible for.",
                        max_length=1024,
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("vendor"),
                models.Model,
            ),
        ),
    ]
