# Generated by Django 5.1.8 on 2025-04-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="homepage",
            field=models.URLField(
                default="https://example.com",
                help_text="Where the user should be directed to if they click this vendor in the vendor list.",
            ),
            preserve_default=False,
        ),
    ]
