# Generated by Django 5.1.8 on 2025-04-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_vendor_homepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="disabled",
            field=models.BooleanField(
                default=False,
                help_text="Should this vendor be hidden? Hidden vendors are not shown at all in the Index.",
            ),
        ),
    ]
