# Generated by Django 5.1.8 on 2025-04-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0003_alter_vendor_disabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={
                "verbose_name": "Sponsored Vendor",
                "verbose_name_plural": "Sponsored Vendors",
            },
        ),
        migrations.AddField(
            model_name="vendor",
            name="referralcode",
            field=models.CharField(
                blank=True, help_text="A referral code, if provided", max_length=256
            ),
        ),
    ]
