# Generated by Django 5.1.8 on 2025-04-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0004_alter_vendor_options_vendor_referralcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="A logo for this vendor. Will be displayed in several places throughout the site at a moderate size",
                null=True,
                upload_to="vendor_logos/",
            ),
        ),
    ]
