# Generated by Django 5.1.8 on 2025-04-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0005_vendor_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="footer",
            field=models.BooleanField(
                default=False,
                help_text="Should this vendor be shown on every page in the footer of the website?",
                verbose_name="Show in footer",
            ),
        ),
    ]
