# Generated by Django 5.1.8 on 2025-04-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0006_vendor_footer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={
                "verbose_name": "sponsored vendor",
                "verbose_name_plural": "sponsored vendors",
            },
        ),
        migrations.AlterField(
            model_name="vendor",
            name="footer",
            field=models.BooleanField(
                default=False,
                help_text="Should this vendor be shown on every page in the footer of the website?",
                verbose_name="show in footer",
            ),
        ),
    ]
