# Generated by Django 5.1.11 on 2025-06-29 22:56

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for this release",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Should this release be hidden from the Index?",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        editable=False,
                        help_text="The human-readable name of this release. It should mirror the original source",
                        max_length=1024,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        editable=False,
                        help_text="A user-facing description of this release. This should mirror the original source",
                    ),
                ),
                (
                    "discovered",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="The time that this release was discovered (added to the database)",
                    ),
                ),
                (
                    "released",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="The time that this release was originally posted",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="The time that this release was originally posted",
                    ),
                ),
                (
                    "release_state",
                    models.IntegerField(
                        blank=True,
                        choices=[(-2, "Dangerous"), (0, "Released"), (1, "Verified")],
                        db_index=True,
                        help_text="What state of release is this item in? If unset, defaults to 0 or inherits from the channel",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "release",
                "verbose_name_plural": "releases",
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("release"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Thumbnail",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for this thumbnail",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="The time that this thumbnail was last refreshed",
                    ),
                ),
                (
                    "origin",
                    models.URLField(
                        blank=True,
                        help_text="A URL to an upstream form of this thumbnail that we're caching from",
                        max_length=512,
                    ),
                ),
                (
                    "small",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        help_text="The small form of this thumbnail",
                        null=True,
                        upload_to="thumbnails/",
                    ),
                ),
                (
                    "large",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        help_text="The large form of this thumbnail",
                        null=True,
                        upload_to="thumbnails/",
                    ),
                ),
            ],
            options={
                "verbose_name": "thumbnail",
                "verbose_name_plural": "thumbnails",
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("release"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ReleaseThumbnail",
            fields=[
                (
                    "thumbnail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="releases.thumbnail",
                    ),
                ),
                (
                    "release",
                    models.OneToOneField(
                        help_text="The release this thumbnail represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnail",
                        to="releases.release",
                    ),
                ),
            ],
            bases=("releases.thumbnail",),
        ),
    ]
