# Generated by Django 5.1.11 on 2025-06-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A user-facing description of this release. This should mirror the original source",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="name",
            field=models.CharField(
                help_text="The human-readable name of this release. It should mirror the original source",
                max_length=1024,
            ),
        ),
    ]
