# Generated by Django 5.1.11 on 2025-06-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0002_alter_release_description_alter_release_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnail",
            name="large",
            field=models.ImageField(
                blank=True,
                help_text="The large form of this thumbnail",
                null=True,
                upload_to="thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="small",
            field=models.ImageField(
                blank=True,
                help_text="The small form of this thumbnail",
                null=True,
                upload_to="thumbnails/",
            ),
        ),
    ]
