# Generated by Django 5.1.11 on 2025-06-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0003_alter_thumbnail_large_alter_thumbnail_small"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="origin",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Manual"), (1, "Lbry")],
                db_index=True,
                help_text="Where did this release come from?",
                null=True,
            ),
        ),
    ]
