# Generated by Django 5.1.11 on 2025-06-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0004_release_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="origin",
            field=models.IntegerField(
                choices=[(0, "Manual"), (1, "Lbry")],
                db_index=True,
                default=0,
                help_text="Where did this release come from?",
            ),
        ),
    ]
