# Generated by Django 5.1.11 on 2025-06-30 00:51

import uuid

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0005_alter_release_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="origin",
            field=models.IntegerField(
                choices=[(0, "Manual"), (1, "Lbry"), (2, "Odysee")],
                db_index=True,
                default=0,
                help_text="Where did this release come from?",
            ),
        ),
        migrations.CreateModel(
            name="DownloadMethod",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for this download method",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "origin",
                    models.IntegerField(
                        choices=[(0, "Manual"), (1, "Lbry"), (2, "Odysee")],
                        db_index=True,
                        default=0,
                        help_text="Where does this download method point to?",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="The URI/CID/magnet link/whatever that this download method represents",
                        max_length=512,
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        help_text="The release this download method is valid for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_methods",
                        to="releases.release",
                    ),
                ),
            ],
            options={
                "verbose_name": "download method",
                "verbose_name_plural": "download methods",
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("downloadmethod"),
                models.Model,
            ),
        ),
    ]
