# Generated by Django 5.1.11 on 2025-06-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0006_alter_release_origin_downloadmethod"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="downloadmethod",
            options={
                "ordering": ["origin"],
                "verbose_name": "download method",
                "verbose_name_plural": "download methods",
            },
        ),
        migrations.AlterUniqueTogether(
            name="downloadmethod",
            unique_together={("origin", "release")},
        ),
    ]
