# Generated by Django 5.1.11 on 2025-06-30 01:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0007_alter_downloadmethod_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnail",
            name="updated",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="The time that this thumbnail was last refreshed. If this date is in the future, the thumbnail has a backoff timer set",
            ),
        ),
    ]
