# Generated by Django 5.1.11 on 2025-06-30 01:21

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0008_alter_thumbnail_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for this channel",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Should this channel be hidden from the Index? Hiding a channel also disables indexing it and hides all of its releases",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The human-readable name of this release. It should mirror the original source",
                        max_length=1024,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A user-facing description of this release. This should mirror the original source",
                    ),
                ),
                (
                    "discovered",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="The time that this release was discovered (added to the database)",
                    ),
                ),
                (
                    "release_state",
                    models.IntegerField(
                        blank=True,
                        choices=[(-2, "Dangerous"), (0, "Released"), (1, "Verified")],
                        db_index=True,
                        help_text="What state of release is this item in? If unset, defaults to 0 or inherits from the channel",
                        null=True,
                    ),
                ),
                (
                    "origin",
                    models.IntegerField(
                        choices=[(0, "Manual"), (1, "Lbry"), (2, "Odysee")],
                        db_index=True,
                        default=0,
                        help_text="Where did this release come from?",
                    ),
                ),
            ],
            options={
                "verbose_name": "channel",
                "verbose_name_plural": "channels",
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("channel"),
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="channel",
            field=models.ForeignKey(
                help_text="The channel this release should be attached to. If unset, the release is anonymous",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="releases",
                to="releases.channel",
            ),
        ),
        migrations.CreateModel(
            name="ChannelThumbnail",
            fields=[
                (
                    "thumbnail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="releases.thumbnail",
                    ),
                ),
                (
                    "release",
                    models.OneToOneField(
                        help_text="The channel this thumbnail represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnail",
                        to="releases.channel",
                    ),
                ),
            ],
            bases=("releases.thumbnail",),
        ),
    ]
