# Generated by Django 5.1.11 on 2025-08-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0009_channel_release_channel_channelthumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnail",
            name="blurhash",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The blurhash of this thumbnail. See: https://leanrada.com/notes/css-only-lqip/",
                max_length=1024,
            ),
        ),
    ]
