# Generated by Django 5.1.11 on 2025-08-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0010_thumbnail_blurhash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thumbnail",
            name="blurhash",
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="color",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The dominant color of this thumbnail. Used as a placeholder while the image loads",
                max_length=1024,
            ),
        ),
    ]
