# Generated by Django 5.1.11 on 2025-08-27 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0011_remove_thumbnail_blurhash_thumbnail_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadmethod",
            name="updated",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="The time that this model was last updated. If this date is in the future, the model has a backoff timer set",
            ),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="updated",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="The time that this model was last updated. If this date is in the future, the model has a backoff timer set",
            ),
        ),
    ]
