# Generated by Django 5.1.11 on 2025-08-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0012_downloadmethod_updated_alter_thumbnail_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="origin",
            field=models.IntegerField(
                choices=[
                    (0, "Manual"),
                    (1, "Lbry"),
                    (2, "Odysee"),
                    (3, "Thingiverse"),
                    (4, "Printables"),
                    (5, "Makerworld"),
                    (6, "Torrent"),
                    (7, "Ipfs"),
                ],
                db_index=True,
                default=0,
                help_text="Where did this release come from?",
            ),
        ),
        migrations.AlterField(
            model_name="downloadmethod",
            name="origin",
            field=models.IntegerField(
                choices=[
                    (0, "Manual"),
                    (1, "Lbry"),
                    (2, "Odysee"),
                    (3, "Thingiverse"),
                    (4, "Printables"),
                    (5, "Makerworld"),
                    (6, "Torrent"),
                    (7, "Ipfs"),
                ],
                db_index=True,
                default=0,
                help_text="Where does this download method point to?",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="origin",
            field=models.IntegerField(
                choices=[
                    (0, "Manual"),
                    (1, "Lbry"),
                    (2, "Odysee"),
                    (3, "Thingiverse"),
                    (4, "Printables"),
                    (5, "Makerworld"),
                    (6, "Torrent"),
                    (7, "Ipfs"),
                ],
                db_index=True,
                default=0,
                help_text="Where did this release come from?",
            ),
        ),
    ]
