# Generated by Django 5.1.11 on 2025-08-30 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0013_alter_channel_origin_alter_downloadmethod_origin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="updated",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="The time that this release was last updated",
            ),
        ),
    ]
