# Generated by Django 5.1.11 on 2025-08-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0014_alter_release_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="release",
            name="origin",
        ),
    ]
