# Generated by Django 5.1.11 on 2025-08-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0015_remove_release_origin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="origin",
        ),
    ]
