# Generated by Django 5.1.12 on 2025-09-05 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0016_remove_channel_origin"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="downloadmethod",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="downloadmethod",
            name="origin",
            field=models.IntegerField(
                choices=[
                    (0, "Manual"),
                    (1, "Lbry"),
                    (3, "Thingiverse"),
                    (4, "Printables"),
                    (5, "Makerworld"),
                    (6, "Torrent"),
                    (7, "Ipfs"),
                ],
                db_index=True,
                default=0,
                help_text="Where does this download method point to?",
            ),
        ),
        migrations.CreateModel(
            name="ChannelDownloadMethod",
            fields=[
                (
                    "downloadmethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="releases.downloadmethod",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        help_text="The channel this download method represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_methods",
                        to="releases.channel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("releases.downloadmethod",),
        ),
        migrations.RemoveField(
            model_name="downloadmethod",
            name="release",
        ),
        migrations.CreateModel(
            name="ReleaseDownloadMethod",
            fields=[
                (
                    "downloadmethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="releases.downloadmethod",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        help_text="The release this download method represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_methods",
                        to="releases.release",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("releases.downloadmethod",),
        ),
    ]
