# Generated by Django 5.1.12 on 2025-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0017_alter_downloadmethod_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadmethod",
            name="origin",
            field=models.IntegerField(
                choices=[(0, "Manual"), (1, "Lbry")],
                db_index=True,
                default=0,
                help_text="Where does this download method point to?",
            ),
        ),
    ]
