# Generated by Django 5.1.12 on 2025-09-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0018_alter_downloadmethod_origin"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="downloadmethod",
            unique_together={("origin", "link")},
        ),
    ]
