---
services:
  wireguard:
    image: ${IMAGE_NAME:-lscr.io/linuxserver/wireguard:latest}
    container_name: ${CONTAINER_NAME:-wireguard}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE                          #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE:-America/Chicago}
      - SERVERURL=${SERVER_URL:-vpn.example.com}             #optional
      - SERVERPORT=${SERVER_PORT:-51820}           #optional
      - PEERS=${PEERS:-1}                      #optional
      - PEERDNS=auto                        #optional
      - INTERNAL_SUBNET=${INTERNAL_SUBNET:-10.13.13.0}  #optional
      - ALLOWEDIPS=${ALLOWED_IPS:-0.0.0.0/0}           #optional
      - PERSISTENTKEEPALIVE_PEERS=          #optional
      - LOG_CONFS=true                      #optional
    volumes:
      - ${CONFIG_DIR:-/opt/docker/docker-compose-configs/wireguard/config}:/config
      - /lib/modules:/lib/modules           #optional
    ports:
      - ${SERVER_PORT:-51820}:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
